name: crypto_chateau_dart
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  crypto: ^3.0.2
  ed25519_edwards: ^0.3.1
  x25519: ^0.1.1
  convert: ^3.1.1
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
